matrix:
  include:
    - language: python
      before_script:
        - cd control
      install:
        - pip install -r requirements.txt
        - pip install tox-travis
        - python setup.py install
      script:
        - tox

python:
  - 2.7
  - 3.5