dist: xenial
language: python
sudo: false
python:
- 2.7
- 3.7
before_install: cd control
install:
- pip install tox-travis
- pip install coveralls
script: tox
after_success:
- COVERALLS_PARALLEL=true coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=6UrsGkPwz7jb5B2dTD6Sf0VIdTr1BirPV