matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - cd control
      install:
        - pip install -r requirements.txt
        - pip install tox-travis
        - python setup.py install
      script:
        - tox

